language: python

python:
  - "2.7"

before_install:
  - openssl aes-256-cbc -K $encrypted_50e73d583398_key -iv $encrypted_50e73d583398_iv -in keys.tar.enc -out keys.tar -d

install:
  - pip install jinja2

script: "./build_and_push_all.sh"
